# Generated by Django 4.1.11 on 2023-10-05 23:07

import booking.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=booking.models.BookingDate(verbose_name='Booking Date'),
        ),
    ]
