# Generated by Django 4.2.4 on 2023-09-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('year', models.DateField(auto_created=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.TextField(max_length=30)),
                ('car_title', models.TextField(max_length=30)),
                ('city', models.TextField(max_length=30)),
                ('model', models.TextField(max_length=30)),
                ('body_style', models.TextField(max_length=30)),
                ('fuel_type', models.TextField(max_length=30)),
                ('is_featured', models.TextField(max_length=30)),
            ],
        ),
    ]
