# Generated by Django 4.2.4 on 2023-09-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
    ]
