# Generated by Django 4.1.11 on 2023-10-03 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='Car Image'),
            preserve_default=False,
        ),
    ]
