# Generated by Django 4.1.11 on 2023-10-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=200, verbose_name='Price per day'),
            preserve_default=False,
        ),
    ]
